server:
  port: 8080

spring:
  application:
    name: nooshet-user-service
  datasource:
    url: jdbc:postgresql://postgresql-user:5432/nooshet_user?sslmode=disable
    username: nooshet_user
    password: user_password_123
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  server-url: "http://95.111.228.89"

redis:
  host: redis
  port: 6379

logging:
  level:
    root: INFO
    org.nooshet.user: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: "replace_this_with_a_secure_random_secret_key"
